### PR TITLE
fix(package): update the `transform` scripts to use proper files

### PR DESCRIPTION
**Pull request by KerimRahman**
Related to #17

### CODE REVIEW

**Comment by KerimRahman** [comment]
Hey, @kendrick, could you check and approve if that's the expected result? Thanks!

**Comment by kendrick** [comment]
@sarsenault26, can you take a look at [the output in `dist`](https://github.com/compassion-global-experience/cds-tokens/pull/18/files) and verify it's what you'd expect?

**Comment by kendrick** [comment]
Hey @KerimRahman! Steven mentioned that there were some minor changes to the token architecture that should fix this—I believe he pushed up those changes earlier today.

**Comment by KerimRahman** [comment]
Yeah, seems it's fixed now, deleting the branch.

**Pull request closed without merging**
